<?php

namespace Tests\Feature\Http\Controllers\api\v1;

use App\Models\Lead;
use App\Models\Organization;
use App\Models\Project;
use App\Models\User;

/**
 * Class ProjectEmbeddingControllerTest
 *
 * Run these specific tests
 * php artisan test tests/Feature/Http/Controllers/api/v1/ProjectEmbeddingControllerTest.php
 *
 * @package Tests\Feature\Http\Controllers\api\v1
 */
class ProjectEmbeddingControllerTest extends TestApi
{
    /**
     * Project api endpoint
     */
    const ENDPOINT_PROJECT = '/v1/project';

    /**
     * @var Project
     */
    private Project $project;

    /**
     * @return void
     */
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->project = Project::create([
            'organization_id'   => 1,
            'name'              => $this->faker->colorName(),
            'description'       => $this->faker->text(200),
            'system_prompt'     => $this->faker->text(200),
            'phone_number'      => $this->faker->numerify('+############'),
        ]);
    }

    /**
     * @test
     *
     * @return void
     */
    public function admin_can_store_a_embeddings_for_A_project(): void
    {
        $this->markTestSkipped('Research how to manage vectors in sql lite or how mock that in order to feature test. ');

        $embeddings_data = [ 'data' =>
            [
                '
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu efficitur mauris, at eleifend tortor.
                Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aliquam interdum
                semper libero, non hendrerit felis ultricies molestie. Suspendisse condimentum nunc maximus ante fringilla,
                a volutpat risus dignissim. In ut faucibus ipsum, nec tincidunt sapien. Ut elit turpis, pulvinar quis
                consequat eget, lobortis ac felis. Curabitur pellentesque porttitor est, nec venenatis ante consectetur a.
                In orci turpis, sagittis id ipsum non, interdum dictum ipsum. Quisque porttitor augue id viverra porta.
                ',
                '
                Ut orci metus, sodales vel gravida sit amet, pharetra a lectus. Mauris suscipit risus ac iaculis tincidunt.
                Aenean vel enim ante. Quisque vel vehicula lacus. Pellentesque consequat, augue nec egestas pretium, sem
                velit lobortis quam, eu egestas dui magna nec sapien. Morbi auctor felis est, eu consequat ante varius in.
                Phasellus viverra arcu ac ipsum efficitur, sed pulvinar libero luctus.
                ',
                '
                Duis ornare sem eu mi semper interdum. Nulla facilisi. Fusce consectetur lectus in enim iaculis, nec iaculis
                arcu placerat. In dignissim lobortis nulla vitae accumsan. Vivamus ultricies nisl odio, sit amet consequat
                ipsum volutpat vel. Nullam faucibus sit amet tellus ut dictum. Donec varius pellentesque neque, sit amet
                lobortis lorem finibus sed. In at blandit elit. Praesent ut tellus quis elit aliquam faucibus. Nulla quis
                sagittis sapien. Nulla commodo diam sed metus facilisis, ut consequat nunc sollicitudin. Curabitur ut
                malesuada erat. Donec sapien nibh, venenatis eu tellus a, blandit pellentesque mauris. Vestibulum quis
                tortor eu orci tincidunt commodo. Ut ut lacus sit amet orci finibus tempor.
                '
            ]
        ];

        $response = $this->withHeader('Authorization', 'Bearer ' . $this->getToken())
            ->json('POST', self::ENDPOINT_PROJECT . '/' . $this->project->id . '/embedding', $embeddings_data);

        $response->assertStatus(200);
        $response->assertJsonPath('message', 'Project embeddings have been stored successfully.');
    }

    /**
     * @test
     *
     * @return void
     */
    public function unauthorized_user_can_not_store_project_content(): void
    {
        $response = $this->withHeader('Authorization', 'Bearer ' . $this->faker->word())
            ->json('POST', self::ENDPOINT_PROJECT . '/' . $this->project->id . '/content', []);

        $response->assertStatus(401);
        $response->assertJsonPath('message', 'Unauthenticated.');
    }

    /**
     * @test
     *
     * @return void
     */
    public function no_admin_user_can_not_store_project_content(): void
    {
        $user = User::create([
            'role'              => 'user',
            'name'              => 'Peter',
            'email'             => 'peter.parker@gmail.com',
            'country_code'      => '+57',
            'phone_number'      => '3131234567',
            'full_phone_number' => '+573131234567',
            'password'          => '$2y$10$dmQmyyu./5uEb.Ti/ZeO3e80V8.mbivA4K1b43O9yvjWbvff0J7qK'
        ]);

        $response = $this->withHeader('Authorization', 'Bearer ' . $this->getToken('peter.parker@gmail.com', 'qwerty123'))
            ->json('POST', self::ENDPOINT_PROJECT . '/' . $this->project->id . '/content', []);

        $response->assertStatus(422);
        $response->assertJsonPath('message', 'The current user is not the the organization owner.');
    }

    /**
     * @test
     *
     * @return void
     */
    public function no_owner_user_can_not_store_project_content(): void
    {
        $user = User::create([
            'role'              => 'user',
            'name'              => 'Peter',
            'email'             => 'peter.parker@gmail.com',
            'country_code'      => '+57',
            'phone_number'      => '3131234567',
            'full_phone_number' => '+573131234567',
            'password'          => '$2y$10$dmQmyyu./5uEb.Ti/ZeO3e80V8.mbivA4K1b43O9yvjWbvff0J7qK'
        ]);

        $user_owner = User::create([
            'role'              => 'user',
            'name'              => 'Tony',
            'email'             => 'tony.stark@gmail.com',
            'country_code'      => '+57',
            'phone_number'      => '3130000000',
            'full_phone_number' => '+573130000000',
            'password'          => '$2y$10$dmQmyyu./5uEb.Ti/ZeO3e80V8.mbivA4K1b43O9yvjWbvff0J7qK'
        ]);
        $lead = Lead::create([
            'user_id'           => $user_owner->id,
            'first_name'        => $user_owner->name,
            'last_name'         => $user_owner->last_name,
            'email'             => $user_owner->email,
            'country_code'      => $user_owner->country_code,
            'phone_number'      => $user_owner->phone_number,
            'full_phone_number' => $user_owner->full_phone_number,
        ]);
        $organization = Organization::create([
            'owner_id'      => $user_owner->id,
            'name'          => 'Bigmelo',
            'description'   => 'Initial organization.',
        ]);
        $user_owner->organizations()->attach($organization);
        $project = Project::create([
            'organization_id'       => $organization->id,
            'name'                  => 'Test',
            'description'           => 'Project test.',
            'phone_number'          => '+14150000000',
            'assistant_description' => 'a nice chatbot powering by AI',
            'assistant_goal'        => 'to help all people to answer their questions and doubts',
            'language'              => 'Spanish',
            'default_answer'        => 'Hummmm.',
            'has_system_prompt'     => false
        ]);
        $user_owner->lead->projects()->attach($project);

        $response = $this->withHeader('Authorization', 'Bearer ' . $this->getToken('peter.parker@gmail.com', 'qwerty123'))
            ->json('POST', self::ENDPOINT_PROJECT . '/' . $project->id . '/content', []);

        $response->assertStatus(422);
        $response->assertJsonPath('message', 'The current user is not the the organization owner.');
    }

}
